### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by Alejandro26** [bluevisiontec/GoogleShoppingApi#1]
Error when i try to go to basic config:
Fatal error: Class 'Varien_Gdata_Gshopping_Extension_Control' not found in /home/tiendascom/domains/tiendascom.com/public_html/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/Source/Destinationstates.php on line 28

Magento version: 3.8.1

**Comment by schnere** [comment]
Hi, 

thanks for information. The Module is based on Mage_GoogleShopping. The initial intention is to replace the old module to work with the new GoogleShopping API v2. 

As the new module does not need the Varien_Gdata classes the depencies will be removed in near future. For the moment you can install Mage_GoogleShopping in addition to fix the issue. 
Another solution would be to install only the Varien_Gdate_GoogleShopping classes from here: https://github.com/Zookal/magento-google-shopping/tree/master/lib/Varien/Gdata/Gshopping

Place it under magento_root/lib/Varien/Gdata

**Comment by Alejandro26** [comment]
it's work :).
thanks!!!
