### ISSUE TITLE
$flag->isLocked() equals false

### ISSUE THREAD

**Issue by gmatsuoka** [bluevisiontec/GoogleShoppingApi#11]
Hello,

I'm trying to synchronize items with google, I am redirected to the page "/index.php/admin/googleShoppingApi_items/refresh/store/1/key/" it is all in white.

When debugging the code I realized that the call $flag->isLocked() (ItemsController.php line 197) always returns false.

Can someone help me understand what can cause this?

Thanks!!

**Comment by schnere** [comment]
Hi, please update to latest bugfix release 0.0.7 and try again.
The flag should always return false, expect when an add/update/delete process is currently running...
