### ISSUE TITLE
Warning: include(Google/Config.php)

### ISSUE THREAD

**Issue by jonatanaxe** [bluevisiontec/GoogleShoppingApi#12]
After upgrading to version 0.0.6 getting the following error

2015-03-02T13:58:41+00:00 ERR (3): Warning: include(Google/Config.php): failed to open stream: No such file or directory  in /var/www/vhosts/dev.test.com/lib/Varien/Autoload.php on line 93
2015-03-02T13:58:41+00:00 ERR (3): Warning: include(): Failed opening 'Google/Config.php' for inclusion (include_path='/var/www/vhosts/dev.test.com/app/code/local:/var/www/vhosts/dev.test.com/app/code/community:/var/www/vhosts/dev.test.com/app/code/core:/var/www/vhosts/dev.test.com/lib:.:/usr/share/pear:/usr/share/php')  in /var/www/vhosts/dev.test.com/lib/Varien/Autoload.php on line 93

**Comment by schnere** [comment]
Hi,

if everything works these warnings can be ignored.
This is caused by the current implementation of Google ApiClient. It uses its own autoloader, but Magento tries to load the files, too.

You will get similar warnings for some attributes as they have a fallback to the "Default" attribute.

**Comment by jonatanaxe** [comment]
I've set the attributes but when access manage items an error Error 500 Internal Server Error occurred and the only log that generates and this.

**Comment by schnere** [comment]
Did you update using composer?

**Comment by jonatanaxe** [comment]
not used composer.

**Comment by schnere** [comment]
Unfortunately "Error 500" is not a very detailed error description. 
Please check your server logs, too. You might find there some detail about the error. 

It could be a file permission error. Or you missed something on manual update?

**Comment by jonatanaxe** [comment]
I'm not finding the error :(

I will continue to follow this project, I'll have to buy a module to generate feed short on time.

I'll still find that mistake! :)

Thank @schnere

**Comment by jonatanaxe** [comment]
Hi @schnere :)  I found this log

Notice: Undefined index: files  in ROOT/app/code/core/Mage/Core/Model/Translate.php on line 138

0 ROOT/app/code/core/Mage/Core/Model/Translate.php(138): mageCoreErrorHandler(8, 'Undefined index...', '/var/www/vhosts...', 138, Array)
1 ROOT/app/code/core/Mage/Core/Model/App/Area.php(146): Mage_Core_Model_Translate->init('adminhtml')
2 ROOT/app/code/core/Mage/Core/Model/App/Area.php(121): Mage_Core_Model_App_Area->_initTranslate()
3 ROOT/app/code/core/Mage/Core/Model/App/Area.php(93): Mage_Core_Model_App_Area->_loadPart('translate')
4 ROOT/app/code/core/Mage/Core/Model/App.php(774): Mage_Core_Model_App_Area->load()
5 ROOT/app/code/core/Mage/Core/Controller/Varien/Action.php(512): Mage_Core_Model_App->loadArea('adminhtml')
6 ROOT/app/code/core/Mage/Adminhtml/Controller/Action.php(160): Mage_Core_Controller_Varien_Action->preDispatch()
7 ROOT/app/code/community/BlueVisionTec/GoogleShoppingApi/controllers/Adminhtml/GoogleShoppingApi/OauthController.php(31): Mage_Adminhtml_Controller_Action->preDispatch()
8 ROOT/app/code/core/Mage/Core/Controller/Varien/Action.php(407): BlueVisionTec_GoogleShoppingApi_Adminhtml_GoogleShoppingApi_OauthController->preDispatch()
9 ROOT/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('auth')
10 ROOT/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
11 ROOT/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
12 ROOT/app/Mage.php(684): Mage_Core_Model_App->run(Array)
13 ROOT/index.php(87): Mage::run('', 'store')
14 {main}

**Comment by jonatanaxe** [comment]
Hi @schnere  
I found the problem was not changing the URL FORWARDING

**Comment by mfortin** [comment]
I get this error now.

2015-03-14T14:56:25+00:00 ERR (3): Warning: include(Google/Service/ShoppingContent/Product.php): failed to open stream: No such file or directory  in /home/www/public_html/lib/Varien/Autoload.php on line 94
2015-03-14T14:56:25+00:00 ERR (3): Warning: include(): Failed opening 'Google/Service/ShoppingContent/Product.php' for inclusion (include_path='/home/www/public_html/app/code/local:/home/www/public_html/app/code/community:/home/www/public_html/app/code/core:/home/www/public_html/lib:.:/usr/share/php:/usr/share/pear')  in /home/www/public_html/lib/Varien/Autoload.php on line 94

Seems the google api code has changed as Google/Service/ShoppingContent/Product.php does not exist anymore and you seem to be referring to it in your code. Which version of the google api php client should I be using ?

**Comment by mfortin** [comment]
Or this:

[14-Mar-2015 16:54:56 UTC] PHP Fatal error:  Class 'Google_Service_ShoppingContent_Product' not found in /home/www/public_html/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/Type.php on line 47

Unable to add any products to google shopping yet.

I realize the class is extended in Google/Service/ShoppingContent.php however it does not seem to load properly.

**Comment by schnere** [comment]
@mfortin It would be better to open a new issue instead of commenting on a closed issue.
The warnings of Varian Autoloader can be ignored. The Google API Client files cannot be loaded with Varian Autoloader. The class Google_Service_ShoppingContent_Product is located in the file Google/Service/ShoppingContent.php as you mentioned.

So please check if the Google API Client is installed correctly in vendor/google/apiclient/src/Google/ and vendor/google/apiclient/autoload.php exists.
I do not have any problems with the newest version of Google API Client.
