### ISSUE TITLE
Fatal error: Class 'Google_Config' Google/Client.php on 

### ISSUE THREAD

**Issue by jonatanaxe** [bluevisiontec/GoogleShoppingApi#13]
Hi @schnere, I am facing another problem
Fatal error: Class 'Google_Config' not found in ROOT/vendor/google/apiclient/src/Google/Client.php on line 80

**Comment by schnere** [comment]
Hi, does ROOT/vendor/google/apiclient/src/Google/Client.php contain `require_once realpath(dirname(__FILE__) . '/../../autoload.php');` on line 18?

If yes, please debug the classNames in the autoload.php file...

**Comment by jonatanaxe** [comment]
Hi @schnere line 18
if (!class_exists('Google_Client')) {
  require_once dirname(**FILE**) . '/../autoload.php';
}

**Comment by schnere** [comment]
Did you debug the autoload.php file?
Does it get loaded? Does it try to load Client.php file?

**Comment by 5mehulhelp5** [comment]
Hello Please check this repo and my be you will found your solution 
https://github.com/5mehulhelp5/MagentoExtensions

**Comment by jonatanaxe** [comment]
https://github.com/google/google-api-php-client/issues/502
