### ISSUE TITLE
Manage Items Page Blank

### ISSUE THREAD

**Issue by rundellbj** [bluevisiontec/GoogleShoppingApi#14]
Everything about this works fine so far.   When I got to Catalog > API V2 > Manage Items.   It is just a white page.  Using Magento 1.8.1.0

![image](https://cloud.githubusercontent.com/assets/11273999/6558620/319b72be-c64b-11e4-9104-579db97da35b.png)

**Comment by schnere** [comment]
Please try the latest bugfix release 0.0.7. 
If that doesn't help, enable PHP error logging and provide the messages.

**Comment by rundellbj** [comment]
Here is the error I get.  I'm also running a multi-store setup.  

(3): Warning: require_once(/chroot/home/xyz/xyz.com/html/vendor/google/apiclient/src/Google/Client.php): failed to open stream: No such file or directory  in /chroot/home/xyz/xyz.com/html/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/GoogleShopping.php on line 2

**Comment by schnere** [comment]
Please make sure to install Google Api Client for PHP to MAGENTO_ROOT/vendor .

Source:https://github.com/google/google-api-php-client

**Comment by rundellbj** [comment]
Added the Google API as you suggested.

Does my problem run deeper then your module?  Still getting the blank white screen when I try to manage still.

Here are the new errors I am encountering .

(3): Warning: include(Google/Config.php): failed to open stream: No such file or directory  in /chroot/home/sp/sports.com/html/lib/Varien/Autoload.php on line 93
2015-03-11T13:19:15+00:00 ERR 

(3): Warning: include(): Failed opening 'Google/Config.php' for inclusion (include_path='/chroot/home/sp/sports.com/html/app/code/local:/chroot/home/sp/sports.com/html/app/code/community:/chroot/home/sp/sports.com/html/app/code/core:/chroot/home/sp/sports.com/html/lib:.:/usr/share/pear:/usr/share/php')  in /chroot/home/sp/sports.com/html/lib/Varien/Autoload.php on line 93
2015-03-11T13:19:16+00:00 ERR

**Comment by schnere** [comment]
The warnings you've posted can usually be ignored. Did the require_once warning go away?
Did you also enable PHP error log? Which log messages do you get there?

**Comment by rundellbj** [comment]
Fatal error: Class 'Google_Config' not found in /chroot/home/sp/sports.com/html/vendor/google/apiclient/src/Google/Client.php on line 80 Warning: include(Mage.php): failed to open stream: No such file or directory in /chroot/home/sp/sports.com/html/lib/Varien/Autoload.php on line 93 Warning: include(Mage.php): failed to open stream: No such file or directory in /chroot/home/sp/sports.com/html/lib/Varien/Autoload.php on line 93 Warning: include(): Failed opening 'Mage.php' for inclusion (include_path='/chroot/home/sp/sports.com/html/app/code/local:/chroot/home/sp/sports.com/html/app/code/community:/chroot/home/sp/sports.com/html/app/code/core:/chroot/home/sp/sports.com/html/lib:.:/usr/share/pear:/usr/share/php') in /chroot/home/sp/sports.com/html/lib/Varien/Autoload.php on line 93 Fatal error: Class 'Mage' not found in /chroot/home/sp/sports.com/html/app/code/core/Mage/Core/functions.php on line 244 Warning: include(Mage.php): failed to open stream: No such file or directory in /chroot/home/sp/sports.com/html/lib/Varien/Autoload.php on line 93 Warning: include(Mage.php): failed to open stream: No such file or directory in /chroot/home/sp/sports.com/html/lib/Varien/Autoload.php on line 93 Warning: include(): Failed opening 'Mage.php' for inclusion (include_path='/chroot/home/sp/sports.com/html/app/code/local:/chroot/home/sp/sports.com/html/app/code/community:/chroot/home/sp/sports.com/html/app/code/core:/chroot/home/sp/sports.com/html/lib:.:/usr/share/pear:/usr/share/php') in /chroot/home/sp/sports.com/html/lib/Varien/Autoload.php on line 93 Fatal error: Class 'Mage' not found in /chroot/home/sp/sports.com/html/app/code/core/Mage/Core/Model/Resource/Session.php on line 108

**Comment by 5mehulhelp5** [comment]
Hello Please check this repo and my be you will found your solution 
https://github.com/5mehulhelp5/MagentoExtensions

**Comment by 5mehulhelp5** [comment]
Hello Please check this repo and my be you will found your solution https://github.com/5mehulhelp5/MagentoExtensions

**Comment by schnere** [comment]
Does the file vendor/google/apiclient/autoload.php exist?
Check at vendor/google/apiclient/src/Google/Client.php line 18 for the following code:

``` php
require_once realpath(dirname(__FILE__) . '/../../autoload.php');
```

**Comment by rundellbj** [comment]
Does the file vendor/google/apiclient/autoload.php exist?    Yes
Check at vendor/google/apiclient/src/Google/Client.php line 18 for the following code:

require_once realpath(dirname(**FILE**) . '/../../autoload.php');

This is what I have in my client.php
require_once dirname(**FILE**) . '/../autoload.php';

If I change my client.php to what you suggested I get this error now.

Parse error: syntax error, unexpected ';' in /chroot/home/sp/sports.com/html/vendor/google/apiclient/src/Google/Client.php on line 19

**Comment by schnere** [comment]
Okay, thanks to @damek132 for notice. I will update the readme with a notice.

As metioned in #23 - please do not use the head revision of Google API Client, as this seems to cause the error.
You can download the working 1.1.2 release here: https://github.com/google/google-api-php-client/archive/1.1.2.tar.gz
