### ISSUE TITLE
Warnings and Not sync

### ISSUE THREAD

**Issue by ghost** [bluevisiontec/GoogleShoppingApi#18]
Warning: include(Google/Service/ShoppingContent/Product.php): failed to open stream: No such file or directory  in /chroot/home/website.com/html/lib/Varien/Autoload.php on line 94

Warning: include(Google/Service/ShoppingContent/Product.php): failed to open stream: No such file or directory  in /chroot/home/website.com/html/lib/Varien/Autoload.php on line 94

Warning: include(): Failed opening 'Google/Service/ShoppingContent/Product.php' for inclusion (include_path='/chroot/home/website.com/html/lib/minify:/chroot/home/website.com/html/app/code/local:/chroot/home/website.com/html/app/code/community:/chroot/home/website.com/html/app/code/core:/chroot/home/website.com/html/lib:.:/usr/share/pear:/usr/share/php')  in /chroot/home/website.com/html/lib/Varien/Autoload.php on line 94

**Comment by schnere** [comment]
You can ignore these warnings.
Can you describe "Not sync" further?

**Comment by 5mehulhelp5** [comment]
Hello Please check this repo and my be you will found your solution 
https://github.com/5mehulhelp5/MagentoExtensions

**Comment by nguyenthixuan151** [comment]
I got same problem:

Warning: include(Google/Service/ShoppingContent/Product.php): failed to open stream: No such file or directory in /chroot/home/website.com/html/lib/Varien/Autoload.php on line 94

Warning: include(Google/Service/ShoppingContent/Product.php): failed to open stream: No such file or directory in /chroot/home/website.com/html/lib/Varien/Autoload.php on line 94

Warning: include(): Failed opening 'Google/Service/ShoppingContent/Product.php' for inclusion (include_path='/chroot/home/website.com/html/lib/minify:/chroot/home/website.com/html/app/code/local:/chroot/home/website.com/html/app/code/community:/chroot/home/website.com/html/app/code/core:/chroot/home/website.com/html/lib:.:/usr/share/pear:/usr/share/php') in /chroot/home/website.com/html/lib/Varien/Autoload.php on line 94

There is anybody fixed it?

**Comment by bizzogc** [comment]
I've also got the same problem when trying to sync products, they dont sync. This was a new install not an upgrade from a previous version.
