### ISSUE TITLE
manage items error

### ISSUE THREAD

**Issue by Alejandro26** [bluevisiontec/GoogleShoppingApi#2]
Hi.

When i go to: Catalog -> Google Content Api v2 -> manage items

Fatal error: require_once() [function.require]: Failed opening required '/home/xxxxxx/domains/xxxxxx.com/public_html/vendor/google/apiclient/src/Google/Client.php' (include_path='/home/xxxxx/domains/xxxxx.com/public_html/app/code/local:/home/xxxxxxxx/domains/xxxxxxx.com/public_html/app/code/community:/home/xxxxxxxx/domains/xxxxxxxx.com/public_html/app/code/core:/home/xxxxxxxx/domains/xxxxxxxx.com/public_html/lib:.:/usr/local/lib/php') in /home/xxxxxxxx/domains/xxxxxxxxx.com/public_html/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/GoogleShopping.php on line 2

**Comment by Alejandro26** [comment]
my vendor folder has only empty folders.
Where do I can re-download it?

Thanks.

**Comment by schnere** [comment]
Hi,

this is a known issue for those, who are not upgrading from Mage_GoogleShopping. 
See #1 .

The need to install Varien_GData_GoogleShopping classes will be removed in a later version. 

To fix the issue for now download the Gshopping folder:
https://github.com/Zookal/magento-google-shopping/tree/master/lib/Varien/Gdata/Gshopping

Place it under magento_root/lib/Varien/Gdata

Best regards

**Comment by Alejandro26** [comment]
already had that folder and does not work

**Comment by schnere** [comment]
Oh, sorry. That was my mistake. Your issue is different. 

You will have to download the Google ApiClient from here:
https://github.com/google/google-api-php-client

Place it under magento_root/vendor/google/apiclient

It should look like this:

```
$ ls -a vendor/google/apiclient/
.  ..  autoload.php  composer.json  CONTRIBUTING.md  examples  .gitignore  LICENSE  phpunit.xml.dist  README.md  src  style  tests  .travis.yml
```

The 'src' folder is the important one...

**Comment by Alejandro26** [comment]
now

400 That’s an error.

Error: redirect_uri_mismatch

Application: Sincronizar con Google Shopping

You can email the developer of this application at: xxxxxxx@gmail.com

The redirect URI in the request: http://www.xxxxxxxxx.com/index.php/admin/googleShoppingApi_oauth/auth/ did not match a registered redirect URI.

**Comment by schnere** [comment]
Okay, please take a look at the Configuration part of the [Readme](../blob/master/Readme.md)
You will have to create a project in Google Developer Console.

There you can specify the redirect URI.

After creating the project, adding the redirect URI and add the Client ID&Secret in the module configuration the error should be gone...

**Comment by Alejandro26** [comment]
I already had created and configured on the magento config

![screenshot](https://cloud.githubusercontent.com/assets/5822516/6106519/6ebc2b88-b062-11e4-843a-77d4d2b861fc.jpg)

**Comment by Alejandro26** [comment]
I already had created and configured on the plugin

![screenshot](https://cloud.githubusercontent.com/assets/5822516/6106590/01a70472-b063-11e4-8366-131ada3871cc.jpg)

**Comment by schnere** [comment]
Please check that you've entered the configuration (ClientID & Secret, Merchant Id) correctly in Magento Admin -> System -> Configuration -> BlueVisionTec Modules -> GoogleShoppingApi .

You should do that in StoreView scope and not in Global scope...

As you have posted the image with Client ID&Secret visible before, I would also suggest to update the credentials for security reasons.

**Comment by Alejandro26** [comment]
It's work, thank for your help :)

404 issue was probably end blankspace on my secret id. 
Thanks for advice i create new credentials

:+1:

**Comment by Toweringmedia-clients** [comment]
I am getting this error when clicking on catalog -> google API V2 -> manage items, and manage attributes Fatal error: Class 'Google_Service_ShoppingContent' not found in /home/xxxxxxx/public_html/app/code/community/Zookal/GShoppingV2/controllers/Adminhtml/GShoppingV2/ItemsController.php on line 24 

Magento version 1.8.1

EDIT:
I figured it out - What I did was installed the version by Zookal. I uninstalled Zookal and installed the bluevisiontec version and got closer. 

Now I am getting this:
Fatal error: require_once(): Failed opening required '/home/xxx/public_html/vendor/google/apiclient/src/Google/Client.php' (include_path='/home/xxx/public_html/app/code/local:/home/xxx/public_html/app/code/community:/home/xxx/public_html/app/code/core:/home/xxx/public_html/lib:.:/usr/local/lib/php') in /home/xxx/public_html/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/GoogleShopping.php on line 2

Edit again..
Installed the Google ApiClient 

Now I am getting a 400 page.

Edit.. ITS WORKING!!!!
I must have had the path wrong in the google developers console. I reentered it and it worked!

Thanks to everyone who as contributed to this!!

To anyone getting frustrated. Take it slow and methodical, then go back over every step again and again until you get it working.

This extension is a critical part of my marketing strategy for our clients. It allows you to advertise only for products you have in stock and want to pay for advertising on. 

THANK YOU, THANK YOU, THANK YOU!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
