### ISSUE TITLE
Error (401) User cannot access account XXXXXXX

### ISSUE THREAD

**Issue by aalonsoillice** [bluevisiontec/GoogleShoppingApi#20]
Hi,

I configured all the steps as described in your info and Also added the email account generated in the Google Developers credentials as a user on my Merchant account, But I keep getting the 401 error.

**Comment by 5mehulhelp5** [comment]
i think you should clear cache and cookie of your browser and then you can check once again may be it will work thnks or you should cross check once again your account has that shopping api enable.

Thanks

**Comment by aalonsoillice** [comment]
Hi
Yesterday I spent the whole day clearing Magento cache and trying to access.
I tried today after letting the system "rest" the whole night and IT WORKS!!!!
It may have a really presistent token :)

Thanks

**Comment by 5mehulhelp5** [comment]
yes that why i have told you to clear the browser cache or you can use the different browser
