### ISSUE TITLE
Source model "googleshoppingapi/attribute_source_googleShoppingCategories" not found for attribute "google_shopping_category"

### ISSUE THREAD

**Issue by captainmackerel** [bluevisiontec/GoogleShoppingApi#21]
Hi,
I've (manually) installed the package on a Magento CE 1.9 install. If the module is enabled, I get a blank page (I suspect a 500 error, but nothing is logged). If I disable the module, the site loads OK, but clicking to edit any product throws this error:

Source model "googleshoppingapi/attribute_source_googleShoppingCategories" not found for attribute "google_shopping_category"";i:1;s:3552:"#0 /var/www/vhosts/hostname/httpdocs/app/code/core/Mage/Eav/Model/Entity/Attribute/Abstract.php(387)

We don't have compilation enabled, but do have Magento caching and APC running. I've flushed both to check whether they caused the problem, and have logged in / out of the admin area.

Does anyone know why this might be happening or how to resolve it?

**Comment by captainmackerel** [comment]
I think this is caused by the use of short array tags which are only supported in PHP 5.4+. There are two files I had to change to change the [] style of array back to the older array(). These were:
/BlueVisionTec/GoogleShoppingApi/Model/Attribute/Source/GoogleShoppingCategories.php
/BlueVisionTec/GoogleShoppingApi/sql/googleshoppingapi_setup/upgrade-0.0.1-0.0.2.php

**Comment by schnere** [comment]
Hi, 

you get the error in your first comment, because you have disabled the module. In this case the source model for the created attribute cannot be loaded.
When you get a blank page, enable PHP error logging and post the output. In most cases this happens when the Google API Client library is not installed correctly.
