### ISSUE TITLE
Not able to enter into "catalog > Google Content API v2 > Manage items"

### ISSUE THREAD

**Issue by carlis8** [bluevisiontec/GoogleShoppingApi#22]
Hello,
I have installed your module, and after following all the instructions i got the error of: 

"Uncaught exception 'Exception' with message 'Warning: 
require_once(/var/www/magento_root/vendor/google/apiclient/src/Google/Client.php):
 failed to open stream: No such file or directory  in 
/var/www/magento_root/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/GoogleShopping.php
 on line 2' in 
/var/www/magento_root/app/code/core/Mage/Core/functions.php:245"

I found browsing round here, that i needed to include vendor folder which i downloaded and added it in the supposed properly location. That made the error disappear, which is fine, but now when I enter into "catalog > Google Content API v2 > Manage items" the screen get white and empty, and it doesn't get in. I have activated the warnings, and this is what I get:

"Warning: include(Google/Config.php): failed to open stream: No such file or directory  in /var/www/magento_root/lib/Varien/Autoload.php on line 93
#0 /var/www/magento_root/lib/Varien/Autoload.php(93): mageCoreErrorHandler(2, 'include(Google/...', '/var/www/google...', 93, Array)
#1 /var/www/magento_root/lib/Varien/Autoload.php(93): Varien_Autoload::autoload()
#2 [internal function]: Varien_Autoload->autoload('Google_Config')
#3 /var/www/magento_root/vendor/google/apiclient/src/Google/Client.php(80): spl_autoload_call('Google_Config')
#4 /var/www/magento_root/app/code/community/BlueVisionTec/GoogleShoppingApi/controllers/Adminhtml/GoogleShoppingApi/OauthController.php(80): Google_Client->__construct()
#5 /var/www/magento_root/app/code/core/Mage/Core/Controller/Varien/Action.php(418): BlueVisionTec_GoogleShoppingApi_Adminhtml_GoogleShoppingApi_OauthController->authAction()
#6 /var/www/magento_root/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('auth')
#7 /var/www/magento_root/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /var/www/magento_root/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 /var/www/magento_root/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /var/www/magento_root/index.php(90): Mage::run('default', 'store')
#11 {main}"

Could you help please?
Thanks in advance.
Carlos

**Comment by 5mehulhelp5** [comment]
use this one https://github.com/5mehulhelp5/MagentoExtensions

**Comment by pasujemito** [comment]
Make sure that you download a stable version of Google API:
https://github.com/google/google-api-php-client/releases

**Comment by CharliBeatsss** [comment]
Ok, version 1.1.2 worked for me. Thanks!
