### ISSUE TITLE
/vendor/google/apiclient/src/Google/Http/REST.php:83

### ISSUE THREAD

**Issue by jonatanaxe** [bluevisiontec/GoogleShoppingApi#24]
Hello I'm having another problem :( when I send the products to the google shopping

2015-03-21T03:55:47+00:00 ERR (3): 
exception 'Google_Service_Exception' with message 'Error calling POST https://www.googleapis.com/content/v2/100508066/products: (400) Unknown field name: adwords_labels' in /var/ROOT.com/vendor/google/apiclient/src/Google/Http/REST.php:83
Stack trace:
#0 /var/ROOT.com/vendor/google/apiclient/src/Google/Http/REST.php(41): Google_Http_REST::decodeHttpResponse(Object(Google_Http_Request), Object(Google_Client))
#1 /var/ROOT.com/vendor/google/apiclient/src/Google/Client.php(564): Google_Http_REST::execute(Object(Google_Client), Object(Google_Http_Request))
#2 /var/ROOT.com/vendor/google/apiclient/src/Google/Service/Resource.php(227): Google_Client->execute(Object(Google_Http_Request))
#3 /var/ROOT.com/vendor/google/apiclient/src/Google/Service/ShoppingContent.php(1014): Google_Service_Resource->call('insert', Array, 'Google_Service_...')
#4 /var/ROOT.com/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/GoogleShopping.php(180): Google_Service_ShoppingContent_Products_Resource->insert('100508066', Object(Google_Service_ShoppingContent_Product))
#5 /var/ROOT.com/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/Service/Item.php(47): BlueVisionTec_GoogleShoppingApi_Model_GoogleShopping->insertProduct(Object(Google_Service_ShoppingContent_Product), '1')
#6 /var/ROOT.com/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/Item.php(86): BlueVisionTec_GoogleShoppingApi_Model_Service_Item->insert(Object(BlueVisionTec_GoogleShoppingApi_Model_Item))
#7 /var/ROOT.com/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/MassOperations.php(79): BlueVisionTec_GoogleShoppingApi_Model_Item->insertItem(Object(Mage_Catalog_Model_Product))
#8 /var/ROOT.com/app/code/community/BlueVisionTec/GoogleShoppingApi/controllers/Adminhtml/GoogleShoppingApi/ItemsController.php(130): BlueVisionTec_GoogleShoppingApi_Model_MassOperations->addProducts(Array, '1')
#9 /var/ROOT.com/app/code/core/Mage/Core/Controller/Varien/Action.php(418): BlueVisionTec_GoogleShoppingApi_Adminhtml_GoogleShoppingApi_ItemsController->massAddAction()
#10 /var/ROOT.com/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('massAdd')
#11 /var/ROOT.com/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /var/ROOT.com/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 /var/ROOT.com/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /var/ROOT.com/index.php(87): Mage::run('', 'store')
#15 {main}

**Comment by jonatanaxe** [comment]
This can be wrong configuration?

**Comment by rundellbj** [comment]
Are you trying to MAP a custom field "adwords_labels" to a Google content attribute?   In your attribute settings?

**Comment by jonatanaxe** [comment]
My attribute
![ss](https://cloud.githubusercontent.com/assets/2486808/6804232/5a62aeac-d21b-11e4-86c8-3b02e1207494.jpg)

**Comment by schnere** [comment]
You do not have to map the Google Shopping Category, this is done automatically. I think you should also remove the mapping of "URL key" => "Labels". This might be the source of your error.

**Comment by rundellbj** [comment]
This maybe a little off you topic, but don't you need a UPC/EAN  => GTIN

**Comment by schnere** [comment]
@rundellbj it depends on category and country. In Germany you need 2 out of 3 GTIN, Brand, MPN

**Comment by jonatanaxe** [comment]
Very good @schnere :) that's right.

I sent the products but not yet appeared google shopping it takes to appear? 
thanks :)

**Comment by schnere** [comment]
If you see a message "Products were added to Google Shopping account." at System -> Notifications everything should be right. It takes a few minutes to see the products in your Merchants account.

**Comment by jonatanaxe** [comment]
Is still generating a log system.log and this normal?

**Comment by schnere** [comment]
Yes, you will see some warnings because of the Magento autoloader. You can ignore these warnings. It's on my TODO list to get rid of this warnings, but its not the highest priority...

**Comment by jonatanaxe** [comment]
Thanks @schnere :)
