### ISSUE TITLE
Tables not created?  Suggestions?

### ISSUE THREAD

**Issue by kellenw** [bluevisiontec/GoogleShoppingApi#26]
I followed the manual installation directions, but I'm getting the following error when clicking on CATALOG>>GOOGLE CONTENT API V2>>MANAGE ITEMS:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'zadmin_alliedmage.googleshoppingapi_items' doesn't exist, query was: SELECT COUNT(*) FROM `googleshoppingapi_items` AS `main_table`
 LEFT JOIN `catalog_product_entity_varchar` AS `p_d` ON p_d.attribute_id=96 AND p_d.store_id='0' AND main_table.product_id=p_d.entity_id
 LEFT JOIN `catalog_product_entity_varchar` AS `p` ON p.attribute_id=96 AND p.store_id=main_table.store_id AND main_table.product_id=p.entity_id
 LEFT JOIN `googleshoppingapi_types` AS `types` ON main_table.type_id=types.type_id WHERE (main_table.store_id IN ('1'))

**Comment by schnere** [comment]
Did you install version 0.1.0? Do you have a row with code = googleshoppingapi_setup in the core_resource database table?

**Comment by kellenw** [comment]
Hi Schnere,

Thanks for your reply.  I downloaded and installed the package that was available yesterday using the "Download Zip" button to the right of the branch list.  I have googleshoppingapi_setup (shows version 0.1.0) as well as googleshopping_setup (shows 1.6.0.0.1) rows in core_resource.  I'm running Magento 1.9.1.  This was recently upgraded from v 1.7.2.  I used to use the core google content extension when we were on 1.7.2, but thought I'd try out your updated API v2 extension, since the old API v1 extension is not available in 1.9.1.  I can access the extension configuration just fine and make changes without errors.  The google shopping tab does not appear in the left margin of the product edit screen though, which I imagine is related to the table issue as well.

Thanks,
Kellenw

**Comment by schnere** [comment]
Okay, please check if there is any googleshoppingapi_\* table in your database. 

If not delete the row googleshoppingapi_setup from core_resource table, empty the cache and open your Magento backend. This will should run the install script again. Please tell me if you see any errors (check system.log with debugging enabled). 

And, please make a backup before doing this ;)

**Comment by kellenw** [comment]
blank screen on frontend and backend now.

**Comment by kellenw** [comment]
I just tried to restore from my db backup... failed. Backup file was corrupted. I'm embarrassed to say, my production site was offline temporarily.  I disabled the extension in /app/etc/modules/BlueVisionTec_GoogleShoppingApi.xml which restored the site for now, but I am unable to edit products in the admin.

I now have googleshoppingapi_attributes,googleshoppingapi _items and googleshoppingapi_types tables in the database. However, I now get the following error when trying to edit a product in the admin:
Source model "googleshoppingapi/attribute_source_googleShoppingCategories" not found for attribute "google_shopping_category"

I still have the extension disabled.

**Comment by schnere** [comment]
Hi, pleas post your php log. For that you can uncomment the ini_set in your index.php file.

After that, for a quick fix you can disable the module in app/etc/modules/... 
Change true to false and emtpy the cache. Then your site should be online again.

**Comment by kellenw** [comment]
Hi Schnere,

Is this what you're looking for?  (I replaced my real user folder name with XXXX as it's my domain name):

Source model "googleshoppingapi/attribute_source_googleShoppingCategories" not found for attribute "google_shopping_category"

Trace:
0 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Eav/Model/Entity/Attribute/Abstract.php(387): Mage::exception('Mage_Eav', 'Source model "g...')
1 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(201): Mage_Eav_Model_Entity_Attribute_Abstract->getSource()
2 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Edit/Tab/Attributes.php(70): Mage_Adminhtml_Block_Widget_Form->_setFieldset(Array, Object(Varien_Data_Form_Element_Fieldset), Array)
3 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(144): Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Attributes->_prepareForm()
4 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Core/Block/Abstract.php(918): Mage_Adminhtml_Block_Widget_Form->_beforeToHtml()
5 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Edit/Tabs.php(79): Mage_Core_Block_Abstract->toHtml()
6 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Core/Block/Abstract.php(293): Mage_Adminhtml_Block_Catalog_Product_Edit_Tabs->_prepareLayout()
7 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Codnitive_Extifcon_Model_Core_Layout))
8 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('adminhtml/catal...', 'product_tabs')
9 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('adminhtml/catal...', 'product_tabs')
10 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
11 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
12 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
13 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
14 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Adminhtml/Controller/Action.php(275): Mage_Core_Controller_Varien_Action->loadLayout(Array, true, true)
15 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Adminhtml/controllers/Catalog/ProductController.php(250): Mage_Adminhtml_Controller_Action->loadLayout(Array)
16 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Catalog_ProductController->editAction()
17 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
18 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
19 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
20 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/Mage.php(684): Mage_Core_Model_App->run(Array)
21 /var/zpanel/hostdata/zadmin/public_html/XXXX_com/index.php(87): Mage::run('', 'store')
22 {main}

**Comment by kellenw** [comment]
I also got the following in the system.log:
2015-03-24T23:05:40+00:00 ERR (3): Warning: include(Mage/Googleshoppingapi/Model/Attribute/Source/GoogleShoppingCategories.php): failed to open stream: No such file or directory  in /var/zpanel/hostdata/zadmin/public_html/XXXX_com/lib/Varien/Autoload.php on line 94
2015-03-24T23:05:40+00:00 ERR (3): Warning: include(Mage/Googleshoppingapi/Model/Attribute/Source/GoogleShoppingCategories.php): failed to open stream: No such file or directory  in /var/zpanel/hostdata/zadmin/public_html/XXXX_com/lib/Varien/Autoload.php on line 94
2015-03-24T23:05:40+00:00 ERR (3): Warning: include(): Failed opening 'Mage/Googleshoppingapi/Model/Attribute/Source/GoogleShoppingCategories.php' for inclusion (include_path='/var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/local:/var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/community:/var/zpanel/hostdata/zadmin/public_html/XXXX_com/app/code/core:/var/zpanel/hostdata/zadmin/public_html/XXXX_com/lib:.:/usr/share/php:/usr/share/pear')  in /var/zpanel/hostdata/zadmin/public_html/XXXX_com/lib/Varien/Autoload.php on line 94

**Comment by schnere** [comment]
Good Morning. 

You get the errors, because the module is disabled. There is a product attribute added which depends on the module...

Please check your core_resource table for googleshoppingapi_setup again.
As the tables were created an the attribute exists, it should be there again?

So the database installation should have been successful.

Now I'd like to see the PHP error_log when you get the blank page. (Log to file or ini_set("display_errors","On");)

May it be that you did not install Google ApiClient in vendor/... ? 
Did you install the module via composer or manually?

**Comment by kellenw** [comment]
Hi Schnere, and good morning to you too. :-)

I installed the extension manually (no composer).
- The autoload.php file is located in MAGENTO-ROOT/vendor/google/apiclient/
- The auth, cache, http, IO and other folders and files such as Client.php, Collection.php, Config.php and others are located in MAGENTO-ROOT/vendor/google/apiclient/src/Google/
- The googleshoppingapi_setup line no longer exists in the core_resource table.  I attempted to try to reinstall the extension again by deleting this record, but upon clearing the cache, I received an error on both the frontend and admin, that prevented me from accessing anything, so I had to disable the extension again to keep the site working.  The googleshoppingapi_setup line was not recreated this time.  It currently does not exist.
- The googleshoppingapi_items, googleshoppingapi_types and googleshoppingapi_attributes tables exist, but appear to be empty (zero rows).  Maybe that's normal at this stage.  I just thought I'd mention it in case it's important.

I get this error with the extension disabled (which you've clarified happens because the extension is disabled):
Source model "googleshoppingapi/attribute_source_googleShoppingCategories" not found for attribute "google_shopping_category"

I get this error when I enable the extension (it tries to reinstall but fails due to existing tables):
Error in file: "/var/zpanel/hostdata/zadmin/public_html/alliedaqua_com/app/code/community/BlueVisionTec/GoogleShoppingApi/sql/googleshoppingapi_setup/install-0.0.1.php" - SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'googleshoppingapi_types' already exists, query was: CREATE TABLE `googleshoppingapi_types` (
  `type_id` int UNSIGNED NOT NULL auto_increment COMMENT 'Type ID' ,
  `attribute_set_id` smallint UNSIGNED NOT NULL COMMENT 'Attribute Set Id' ,
  `target_country` varchar(2) NOT NULL default 'DE' COMMENT 'Target country' ,
  PRIMARY KEY (`type_id`),
  UNIQUE `UNQ_GOOGLESHOPPINGAPI_TYPES_ATTRIBUTE_SET_ID_TARGET_COUNTRY` (`attribute_set_id`, `target_country`),
  CONSTRAINT `FK_GOOGLESHOPPINGAPI_TYPES_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DELETE CASCADE ON UPDATE NO ACTION
) COMMENT='Google Content Item Types link Attribute Sets' ENGINE=INNODB charset=utf8 COLLATE=utf8_general_ci
1. If I delete the googleshoppingapi_items, googleshoppingapi_types and googleshoppingapi_attributes tables, will this allow the installation to proceed?  Is it safe?
2. I can't access my products in admin currently.  Will deleting the tables above at least allow me to access and edit my products again, until I can take more time to get the installation to work? Or do I need to perform other database edits too?  I really need to edit some prices and inventory, as this is a production site.

I'm thinking it might be best to uninstall the remaining pieces of the extension on the production site for now, so I can get it operating normally.  Would it be possible for you to provide directions on how to do that?  Then, I can install it on a development install to troubleshoot further without interrupting the live site.

Thanks so much for your time and assistance!  I really appreciate it.

**Comment by schnere** [comment]
This is normal as the tables were already created. Instead of deleting the tables, I would suggest do rename the file app/code/community/BlueVisionTec/GoogleShoppingApi/sql/googleshoppingapi_setup/install-0.0.1.php to install-0.0.1.php.bak or similar.

After that, re-enable the module, empty the cache again and please post the PHP log of the blank page.

The googleshoppingapi_setup entry should then be there again in core_resource table.

Which version of Google API Client did you install (you should take 1.1.2): https://github.com/google/google-api-php-client/releases

**Comment by kellenw** [comment]
I followed your directions, but instead of a blank page I got the following error when the cache management page tried to refresh after I emptied the cache.  I am then locked out out of the admin (The error occurs on the frontend too), until I disable the extension:
Fatal error: Class 'Mage_Googleshopping_Helper_Data' not found in /var/zpanel/hostdata/zadmin/public_html/XXXXX_com/app/Mage.php on line 547

---

The googleshoppingapi_setup entry is restored in core_resource now, but it says 0.1.0 for version (resource version) and NULL for data_version.  I thought this said 0.1.0 for both when I did it the first time.  Not sure if that matters.

The Google Shopping option under Catalog in magento admin does not exist any more.  It did the first time I tried to install, but has been gone ever since I tried the first repair.  Not sure if that's important at this point or not.

**Comment by schnere** [comment]
Okay, I see. Sorry that was my mistake again.
Please rename mysql4-data-install-0.0.1.php to mysql4-data-install-0.0.1.php.bak or similar, too.

**Comment by kellenw** [comment]
Progess... sweet progress!  Okay, it looks like the extension installed without errors now, and I am able to access products in admin, and the Google API v2 option is back in the Catalog menu!  I am also able to get through the Oauth process, and into the add items screen.  I'll play around a bit and report back!  Thanks schnere!!!!  Once I get this going smoothly I'd like to send a donation your way.  Do you have a way to accept donations?

Thanks,
Kellenw

**Comment by schnere** [comment]
I am happy that we could manage to get the module installed :)
Let me know, if everything else is working as you expect.

Really nice of you, that you think about a donation. You could use my PayPal account to send it: r.schneidewind@bluevisiontec.eu .

Best regards,

schnere

**Comment by phanikumar111** [comment]
I got this exception in googleshoppingapi -> Manage attributes -> Add attribute Mapping  "Can't create Attribute Set Mapping" in the TypesController.php. 

Thanks
Phani

**Comment by schnere** [comment]
@phanikumar111 it would be better to open a knew issue for this...
Please check if the database tables are created correctly. You should see 4 tables starting with "googleshopping_" .
And please provide the data provided in exception.log when you get this error.

**Comment by phanikumar111** [comment]
I am getting this exception
exception 'Exception' with message 'Warning: Invalid argument supplied for foreach()  in /var/www/googleshopping/app/code/community/BlueVisionTec/GoogleShoppingApi/Block/Adminhtml/Types/Edit/Form.php on line 115' in /var/www/googleshopping/app/code/core/Mage/Core/functions.php:245
Stack trace:

only three tables created

googleshopping_attributes
googleshopping_items
googleshopping_types

**Comment by schnere** [comment]
Which Magento version are you on?
Did you edit the config.xml of the module?

You should not get this error as allowed_countries are defined statically in the module config.
The array should never be empty...
You might debug the output in the mentioned file e.g. Mage::log($_allowed);

**Comment by phanikumar111** [comment]
1.9.1.0. yes i copied allowed_countries to the config.xml.

**Comment by schnere** [comment]
From where did you copy allowed_countries?
The countries supported by Google are already implemented: https://github.com/bluevisiontec/GoogleShoppingApi/blob/master/app/code/community/BlueVisionTec/GoogleShoppingApi/etc/config.xml

**Comment by phanikumar111** [comment]
ya same thing in config.xml.

**Comment by schnere** [comment]
Please replace the config.xml by the upstream version, clear the cache and try again.
Did you change anything else?

**Comment by kikorro** [comment]
Hi:
And what to do if i need to uninstall the module? How to delete that product attribute added which depends on the module...

Thanks

**Comment by Digiraf** [comment]
hey there,
am having setup issues too. i get googleshoppingapi_items' doesn't exist, query was: SELECT...
I tried all above but no luck

**Comment by schnere** [comment]
Did you delete the cache after installing the module?
Can you check in your database?
```
SELECT * FROM core_resource WHERE code="googleshoppingapi_setup"
```
