### ISSUE TITLE
Add other country

### ISSUE THREAD

**Issue by Zydol** [bluevisiontec/GoogleShoppingApi#28]
Hello,
How can I add other country like Poland?
Can you help me?
Best Regards

**Comment by schnere** [comment]
Hi, 

GoogleShopping is not available in all countries, therefore only a few countries are available in the module.
But Poland was added to the countries where GoogleShopping is available, so I will add it in the module configuration with the next commit..

Beste regards,

schnere

**Comment by Zydol** [comment]
Thank you Schnere. Is complicated? maybe I'll try?

**Comment by schnere** [comment]
As the countries should be available for everyone, I will add it now. 
To see how it's done take a look at the allowed_countries in config.xml .

**Comment by Zydol** [comment]
I'm just make the same ;)
But now when I go to catalog/google content apiV2 load error:

Warning: include(Google/Config.php): failed to open stream: No such file or directory  in /var/www/virtual/gardenowo.pl/htdocs/lib/Varien/Autoload.php on line 94

#0 /var/www/virtual/gardenowo.pl/htdocs/lib/Varien/Autoload.php(94): mageCoreErrorHandler(2, 'include(Google/...', '/var/www/virtua...', 94, Array)
#1 /var/www/virtual/gardenowo.pl/htdocs/lib/Varien/Autoload.php(94): Varien_Autoload::autoload()
#2 [internal function]: Varien_Autoload->autoload('Google_Config')
#3 /var/www/virtual/gardenowo.pl/htdocs/vendor/google/apiclient/src/Google/Client.php(81): spl_autoload_call('Google_Config')
#4 /var/www/virtual/gardenowo.pl/htdocs/app/code/community/BlueVisionTec/GoogleShoppingApi/controllers/Adminhtml/GoogleShoppingApi/OauthController.php(80): Google_Client->__construct()
#5 /var/www/virtual/gardenowo.pl/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): BlueVisionTec_GoogleShoppingApi_Adminhtml_GoogleShoppingApi_OauthController->authAction()
#6 /var/www/virtual/gardenowo.pl/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('auth')
#7 /var/www/virtual/gardenowo.pl/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /var/www/virtual/gardenowo.pl/htdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 /var/www/virtual/gardenowo.pl/htdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /var/www/virtual/gardenowo.pl/htdocs/index.php(80): Mage::run('', 'store')
#11 {main}

Any idea?

**Comment by schnere** [comment]
Did you install Google API Client 1.1.2?
https://github.com/google/google-api-php-client/releases

**Comment by Zydol** [comment]
yeah in /htdocs/vendor/google/apiclient

**Comment by schnere** [comment]
Please make sure that you use version 1.1.2 and not the head revision of Google API Client.

Does line 18 in vendor/google/apiclient/src/Google/Client.php look like the following?

``` php
require_once realpath(dirname(__FILE__) . '/../../autoload.php');
```

**Comment by Zydol** [comment]
Looks same

```
require_once realpath(dirname(__FILE__) . '/../../autoload.php');

class Google_Client
{
 const LIBVER = "1.1.2";
 const USER_AGENT_SUFFIX = "google-api-php-client/";
```

**Comment by schnere** [comment]
Mhm, if you enable php error_log, do you get any errors?
You should debug if vendor/google/apiclient/src/Google/Client.php and vendor/google/apiclient/autoload.php gets loaded.

**Comment by Zydol** [comment]
no, I dont see any new error

**Comment by schnere** [comment]
Can you debug if vendor/google/apiclient/src/Google/Client.php and vendor/google/apiclient/autoload.php are getting loaded?

If you would prefer paid installation support, please contact me at r.schneidewind@bluevisiontec.eu

**Comment by Zydol** [comment]
no they aren't My customer now want to buy some working extension. I'm just want to help him.
