### ISSUE TITLE
Adding custom attribute

### ISSUE THREAD

**Issue by ter700** [bluevisiontec/GoogleShoppingApi#29]
I'm trying to add the custom attribute 'identifier exists'.

When i map it like this:
![capture](https://cloud.githubusercontent.com/assets/6646005/6834982/fe9d48f2-d337-11e4-8d48-324c87ff7941.PNG)

I get the following error:
exception 'Google_Service_Exception' with message 'Error calling POST https://www.googleapis.com/content/v2/8980377/products: (400) Unknown field name: identifier_exists' in /vendor/google/apiclient/src/Google/Http/REST.php:83

How do i translate identifier_exists to an attribute name google will understand, like "identifier exists"? I've tried adding it to config.xml as a translation but no dice.

**Comment by schnere** [comment]
Hi, 

there are fields for custom attributes in Google Shopping API. I will take a look at it and see how this can get implemented. But can you tell me the reason why you want to upload this?

**Comment by ter700** [comment]
Thanks for your quick answers Schnere!

Because our store has a lot of 'custom goods'. 
Google requires the flag 'identifier exists' to be set to 'false' if you send custom goods, and if you do you can withhold the GTIN/MPN and brand attributes. 
(Google summary of attribute requirements: https://support.google.com/merchants/answer/1344057 )

Edit:
It seems that custom clothing does not fall under the category 'Custom goods' at google, so i'm trying to map the product as you should map clothing. However the age group mapping keeps giving me the same error as above:

exception 'Google_Service_Exception' with message 'Error calling POST https://www.googleapis.com/content/v2/8980377/products: (400) Unknown field name: age_group' in /vendor/google/apiclient/src/Google/Http/REST.php:83

The age group attribute has the value 'adult' (i tried 'Adult' as well), so the value should be correct.
Mapping like this:
![capture](https://cloud.githubusercontent.com/assets/6646005/6853746/450ba5b2-d3ed-11e4-8a1a-d2561da6062c.PNG)

What am i missing here?

**Comment by schnere** [comment]
Okay, age_group should be ageGroup. I've added a line that transforms all attribute names to lower camel case. Should be fixed with next commit.
