### ISSUE TITLE
Flag does not unset as false after sync

### ISSUE THREAD

**Issue by AshleshaGawade** [bluevisiontec/GoogleShoppingApi#30]
Hello,

Everything is working fine with the extension, products are also getting synced to google merchant.
But i run a cron to sync the products daily. There are almost 9000 and above products.
After approximately 6000 or 7000 products(do not know the exact number) synced the process stops but the flag is not unset.

What could be the exact problem?
As i am not getting any error nor any notification.

**Comment by schnere** [comment]
Hi,

that might be a problem with a timeout. Please enable PHP error_log to file and check the output.
For such a huge amount of products to sync daily we might have to implement some improvements.

When you say you've set up a cron job - how did you handle the authentication?

**Comment by AshleshaGawade** [comment]
Thanks.
By Using .p12 file authentication.
Server application credentials.
