### ISSUE TITLE
table [prefix]_eav_attribute_set doesn't exist

### ISSUE THREAD

**Issue by lewisak** [bluevisiontec/GoogleShoppingApi#31]
I have got the extension installed and working on a test server, however, when I try to install on a full copy of my production server I get the error below.

I think the only difference between the test and production environment is that the production install uses a table prefix, the test server doesn't. I don't know if this is relevant but the table prefix contains upper and lowercase letters, but in the error log the prefix is listed as all lowercase.

a:5:{i:0;s:271:"Error in file: "/var/www/vhosts/xxxxxxxxx/httpdocs/app/code/community/BlueVisionTec/GoogleShoppingApi/sql/googleshoppingapi_setup/install-0.0.1.php" - SQLSTATE[42S02]: Base table or view not found: 1146 Table '@@@@@@.*******_eav_attribute_set' doesn't exist";i:1;s:1088:"#0 /var/www/vhosts/xxxxxxxx/httpdocs/app/code/core/Mage/Core/Model/Resource/Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')

xxxxx = my domain name
@@@@ = my db name
*****\* = my db prefix.

**Comment by schnere** [comment]
Yourdbprefix_eav_attribute_set should exist in a working Magento installation, so it seems that it is a problem with the prefix containing uppercase letters.
As the "addAttribute" method is used you might debug this, to see where the prefix is transformed to lower case...

**Comment by lewisak** [comment]
Hi schnere

Changing the table prefix to all lowercase has fixed the issue. Thanks.

I didn't check where the strtolower was occurring though,sorry.
