### ISSUE TITLE
Unable to update google_shopping_category normally

### ISSUE THREAD

**Issue by AQuackenbos** [bluevisiontec/GoogleShoppingApi#34]
The google_shopping_category attribute, which assigned itself automatically, does not seem to save correctly.  Example code:

```
$product = Mage::getModel('catalog/product')
        ->load(1);
echo 'GSC: '.$product->getGoogleShoppingCategory()."\n"; //"567"
$product->setData('google_shopping_category',5701);
echo 'GSC: '.$product->getGoogleShoppingCategory()."\n"; //"5701"
$product->save();
```

But after save, it stays at 567.  `$product->setGoogleShoppingCategory(5701)`  also failed.  Not sure if I'm missing some special properties of the attribute; I know it loads the source data from a flat file, but didn't think that would impact saving the data as it's just an int stored in the EAV tables.

**Comment by schnere** [comment]
This works for me:

``` php
Mage::app()->setCurrentStore($storeId);
$product = Mage::getModel('catalog/product')->load(1)->setStoreId($storeId);
$product->setGoogleShoppingCategory(1234)->save();
```
