### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by nohart** [bluevisiontec/GoogleShoppingApi#35]
Hello, I dont know if this is the correct place to ask for help. But after installing I go to Catalog -> Google Content API v2 -> Manage Items, the following error page opens - Everything else seems to work ok in the back end. I am running Magento v1.7.0.2 I had the Google Shopping v1 installed previously and it was running great. This version seemed to pick everything up (settings etc) but Manage Items page wont open. Can anyone point me in the right direction to a fix?

Warning: include(Google/Config.php): failed to open stream: No such file or directory  in /home/MyWebSite/public_html/lib/Varien/Autoload.php on line 93
#0 /home/MyWebSite/public_html/lib/Varien/Autoload.php(93): mageCoreErrorHandler(2, 'include(Google/...', '/home/MyWebSite/pu...', 93, Array)
#1 /home/MyWebSite/public_html/lib/Varien/Autoload.php(93): Varien_Autoload::autoload()
#2 [internal function]: Varien_Autoload->autoload('Google_Config')
#3 /home/MyWebSite/public_html/vendor/google/apiclient/src/Google/Client.php(81): spl_autoload_call('Google_Config')
#4 /home/MyWebSite/public_html/app/code/community/BlueVisionTec/GoogleShoppingApi/controllers/Adminhtml/GoogleShoppingApi/OauthController.php(80): Google_Client->__construct()
#5 /home/MyWebSite/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(419): BlueVisionTec_GoogleShoppingApi_Adminhtml_GoogleShoppingApi_OauthController->authAction()
#6 /home/MyWebSite/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('auth')
#7 /home/MyWebSite/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /home/MyWebSite/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 /home/MyWebSite/public_html/app/Mage.class.php(656): Mage_Core_Model_App->run(Array)
#10 /home/MyWebSite/public_html/index.php(87): Mage::run('', 'store')
#11 {main}

**Comment by schnere** [comment]
Hi, did you install Google ApiClient Release 1.1.2?
https://github.com/google/google-api-php-client/archive/1.1.2.tar.gz

**Comment by nohart** [comment]
Yes it looks like it is installed. I ran composer. I have never used Composer but did notice after running it that some files were not installed maybe that happened with the Google ApiClient. There is a folder in [MAGENTO_ROOT]/vendor/google/apiclient/ and it has the files in it. Do I need to install it manually also? Maybe the permissions are not set correctly. I have mostly used Magento Connect to install my extensions. Only a couple have been installed manually. This is the first one I have used Composer for.

**Comment by pasujemito** [comment]
@schnere I was wondering if the extension will support the current 'passing build' of Google API?

**Comment by darrelljr00** [comment]
How do you install the Google api release client ? And also how do you install the composer?

**Comment by darrelljr00** [comment]
im having the same issue. manage items wont open

**Comment by jay-saint** [comment]
I  believe I am having the same issue here.  Installed both GoogleShoppingApi and Google ApiClient Release 1.1.2 via composer.

I receive a white screen when trying to add items and have the following errors in php-error.log file.

```
 PHP Fatal error:  require_once(): Failed opening required '/chroot/home/home_directory/my_website/html/vendor/google/apiclient/src/Google/autoload.php' (include_path='/chroot/home/home_directory/my_website/html/app/code/local:/chroot/home/home_directory/my_website/html/app/code/community:/chroot/home/home_directory/my_website/html/app/code/core:/chroot/home/home_directory/my_website/html/lib:.:/usr/share/pear:/usr/share/php') in /chroot/home/home_directory/my_website/html/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/GoogleShopping.php on line 2
```

Any help is much appreciated.

**Comment by schnere** [comment]
Please take a look at #46

Am 19. Juni 2015 22:06:48 MESZ, schrieb jay-saint notifications@github.com:

> I  believe I am having the same issue here.  Installed both
> GoogleShoppingApi and Google ApiClient Release 1.1.2 via composer.
> 
> I receive a white screen when trying to add items and have the
> following errors in php-error.log file.
> 
> ```
> PHP Fatal error:  require_once(): Failed opening required
> '/chroot/home/home_directory/my_website/html/vendor/google/apiclient/src/Google/autoload.php'
> (include_path='/chroot/home/home_directory/my_website/html/app/code/local:/chroot/home/home_directory/my_website/html/app/code/community:/chroot/home/home_directory/my_website/html/app/code/core:/chroot/home/home_directory/my_website/html/lib:.:/usr/share/pear:/usr/share/php')
> in
> /chroot/home/home_directory/my_website/html/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/GoogleShopping.php
> on line 2
> ```
> 
> Any help is much appreciated.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bluevisiontec/GoogleShoppingApi/issues/35#issuecomment-113628680

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jay-saint** [comment]
@schnere thanks that worked. Everything is back up and working now.
