### ISSUE TITLE
Google returning 'Link' issue

### ISSUE THREAD

**Issue by AlanRuddick** [bluevisiontec/GoogleShoppingApi#37]
Great work on the plugin! So far it's been so easy to use. I've encountered a problem however, which is stopping me submitting my catalogue to google shopping. From what I gather google wants a full URL link to the product. I've found no way of creating this as an attribute and then mapping it, nor do I believe your code sends it (I could be wrong on this one)

This is the error given;

Errors happened while adding products to Google Shopping.
The product "PRODUCT NAME" hasn't been added to Google Content.
Error calling POST https://www.googleapis.com/content/v2/8761712/products: (400) [link] validation/invalid...

Any suggestions would be greatly appreciated as it's had me a bit baffled. I've also attempting sending the url-key in it's place with no luck.

Many thanks,

Alan

**Comment by schnere** [comment]
The link attribute is mapped automatically. So please do not add it manually to the attribute set mapping.
To debug which link is uploaded to google debug the class BlueVisionTec_GoogleShoppingApi_Model_Attribute_Link

**Comment by AlanRuddick** [comment]
Thanks!
