### ISSUE TITLE
google shopping price shows wrong

### ISSUE THREAD

**Issue by punitgadhiya** [bluevisiontec/GoogleShoppingApi#38]
I have Install and configure extension. It is working fine.
In Magento store price shows like this way Excl. BTW: € 180,99 and Incl. BTW: € 219,00. and when product synchronize with google shopping. In google shopping store it shows price exclusive tax. while i want to  display Inclusive tax price. It mean it should show 219 instead of 180.99 how is it possible?
(Note: I have tried mapping attribute with "Display Actual Price" and "Price" but in both case it shows Exclusive Tax Price 180.99).

**Comment by schnere** [comment]
Are you listing your products inside or outside US?

**Comment by punitgadhiya** [comment]
It is for Netherland.

**Comment by punitgadhiya** [comment]
I am using google shopping for country Netherland. Can you please tell me what can i do for this price issue?

**Comment by schnere** [comment]
Okay, you have your price display settings on "Inclunding and excluding tax"? 
Please try the following patch and let me know if it works:

```
--- app/code/community/BlueVisionTec/GoogleShoppingApi/Model/Attribute/Price.php.orig   2015-06-11 14:44:48.690510854 +0200
+++ app/code/community/BlueVisionTec/GoogleShoppingApi/Model/Attribute/Price.php        2015-06-11 14:44:54.674507118 +0200
@@ -38,7 +38,10 @@
         // get tax settings
         $taxHelp = Mage::helper('tax');
         $priceDisplayType = $taxHelp->getPriceDisplayType($product->getStoreId());
-        $inclTax = ($priceDisplayType == Mage_Tax_Model_Config::DISPLAY_TYPE_INCLUDING_TAX);
+        $inclTax = (
+            $priceDisplayType == Mage_Tax_Model_Config::DISPLAY_TYPE_INCLUDING_TAX
+            || $priceDisplayType == Mage_Tax_Model_Config::DISPLAY_TYPE_BOTH
+        );


         // calculate sale_price attribute value
```

**Comment by punitgadhiya** [comment]
@schnere Thank you So much brother. its working fine now. 
Thanks
