### ISSUE TITLE
Uncaught ReferenceError: gContentAttribute is not defined

### ISSUE THREAD

**Issue by AlanRuddick** [bluevisiontec/GoogleShoppingApi#40]
This is more likely to be an error with my magento installation, than your codebase, but support would be appreciated!

When attempting to add an attribute mapping, when clicking the button, I'm present with 'Uncaught ReferenceError: gContentAttribute is not defined' in the console.

Everything else (other than this) appears to be working (I obviously can't submit to google without any mappings though).

Interestingly, I have this installed on an identical magento installation for a different region and have had no issues with the plugin.

Any suggestions?

**Comment by schnere** [comment]
This seems to be a JavaScript error?

Please check if app/design/adminhtml/default/default/template/googleshoppingapi/types/edit/attributes.phtml is loaded correctly.

**Comment by AlanRuddick** [comment]
I can confirm that it is and that the required JS is there too

**Comment by AlanRuddick** [comment]
After taking some time away from debugging this, I've come across what the issue is. The plugin is outputting massive arrays in place of $this->getFieldId() and getAttributesSelectHtml() in attributes.phtml in app/design/adminhtml/default/default/template/googleshoppingapi/types/edit

**Comment by AlanRuddick** [comment]
After changing our hosting environment, and upgrading our PHP version to 5.4, the issue has been reduced to only getAttributesSelectHtml() putting out very large (40mb or so) arrays
