### ISSUE TITLE
Error Fetching oAuth2

### ISSUE THREAD

**Issue by bavington** [bluevisiontec/GoogleShoppingApi#42]
After setting up your extension a few days ago it was working fine. However logging in today, the ability to access the list appears to no longer work, and I'm presented with an error. Any support would be greatly appreciated.

`Trace:
#0 /home/thefurni/public_html/vendor/google/apiclient/src/Google/Client.php(126): Google_Auth_OAuth2->authenticate('4/AXGwhgiQH-1ZP...')
#1 /home/thefurni/public_html/app/code/community/BlueVisionTec/GoogleShoppingApi/controllers/Adminhtml/GoogleShoppingApi/OauthController.php(95): Google_Client->authenticate('4/AXGwhgiQH-1ZP...')
#2 /home/thefurni/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): BlueVisionTec_GoogleShoppingApi_Adminhtml_GoogleShoppingApi_OauthController->authAction()
#3 /home/thefurni/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('auth')
#4 /home/thefurni/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#5 /home/thefurni/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#6 /home/thefurni/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 /home/thefurni/public_html/index.php(86): Mage::run('default', 'store')
#8 {main}`

![screen shot 2015-05-13 at 08 57 52](https://cloud.githubusercontent.com/assets/4979850/7606233/e603293c-f94e-11e4-860b-ceaed5a93c6c.png)

**Comment by darrelljr00** [comment]
Did you ever get this fixed? Im having an auth issue also

**Comment by bavington** [comment]
Hey @darrelljr00, I didn't get to the root cause, I only managed to sort it by uninstalling, and starting again. Seemed to be OK the second time round.

**Comment by darrelljr00** [comment]
When installing the google api do you just place it in the vendor/google/apiclient folder? Or is there a specific google api script to run? Im lost. When I go to manage items it prompts for authentication, I click ok and then it reroutes me back to my homepage. Ive tried everything.

**Comment by bavington** [comment]
You start off by installing the Google API in: [MAGENTO_ROOT]/vendor/google/apiclient/ 
Once you then install the extension (in the regular location), it looks for files within that vender/google/apiclient folder. Have you set up the project in the Google Developer's Console to get the API tokens etc?

**Comment by darrelljr00** [comment]
I have the client id, and client secret . Ive tried everything but it seems like the credentials are not being forwarded to google for verification. Ive checked the developers console and there are no attempts for the api to communicate with google

**Comment by schnere** [comment]
You might want to try out the new ability to use a service account (see updated Readme). 
Please update the module to the newest version (0.2.2) and ensure to use Google API client for PHP in head revision or version 1.1.4 with the following patch:

```
--- vendor/google/apiclient/src/Google/Client.php.orig  2015-06-10 12:15:08.937391432 +0200
+++ vendor/google/apiclient/src/Google/Client.php       2015-06-10 12:15:47.693520083 +0200
@@ -16,7 +16,7 @@
  */

 if (!class_exists('Google_Client')) {
-  require_once dirname(__FILE__) . '/../autoload.php';
+  require_once dirname(__FILE__) . '/autoload.php';
 }

 /**
```

(see https://github.com/google/google-api-php-client/commit/818b20c291b074a609da633d243bf61bcf7dfaac)

**Comment by darrelljr00** [comment]
has the zip file been updated with the new files?

**Comment by schnere** [comment]
You can download the newest version of the Magento Module here: https://github.com/bluevisiontec/GoogleShoppingApi/archive/0.2.2.tar.gz
https://github.com/google/google-api-php-client/archive/1.1.4.tar.gz
For the Google API Client for PHP you should download [this](https://github.com/google/google-api-php-client/archive/1.1.4.tar.gz), place it under vendor/google/apiclient and apply the patch.

You can also apply the patch manually after updating to 1.1.4 by changing line 19 in vendor/google/apiclient/src/Google/Client.php to the following:

``` php
require_once dirname(__FILE__) . '/autoload.php';
```

**Comment by punitgadhiya** [comment]
Can you please look at issue #38 ?

**Comment by darrelljr00** [comment]
Is there a way to bulk assign products to google categories using magmi? I
have thousands of products and cannot assign them manually

**Comment by darrelljr00** [comment]
It seems that the google category  attribute was created so that the data
has to be selected by a drop down. Can we edit it so that we can use text?
That way we should be able to type in a google category number inside a
excel doc and upload via magmi
