### ISSUE TITLE
Adding new attribute promotion_id gives error.

### ISSUE THREAD

**Issue by AshleshaGawade** [bluevisiontec/GoogleShoppingApi#43]
Hello,
I am getting this error when i try to add new attribute promotion_id in googleshoppingapi:
Errors happened while adding products to Google Shopping.
The product "XXX " hasn't been added to Google Content.
Error calling POST https://www.googleapis.com/content/v2/1234/products: (400) Unknown field name: promotion_id

I have added the id to config.xml and created a new file PromotionId.php in Attributes also.
Have also Mapped the attribute in magento backend.

What else is required could you help with this?

**Comment by 5mehulhelp5** [comment]
Please look at these below Info and check is your promotion id value meet those or not.

Merchant Promotions Attribute
For retailers using Merchant Promotions, the 'promotion id' attribute is used in both your products feed and your promotions feed to match products to promotions across the two feeds.

Learn more about Merchant Promotions, including country availability and data feed requirements.

promotion id [promotion_id]
The unique ID of a promotion. For online promotions that apply to specific products, the 'promotion id' in your promotions feed should match this attribute in your products feed so Google knows which products belong to this promotion.

Important:

The 'promotion id' is case sensitive. If you're mapping a specific promotion to a set of products in your products feed, the 'promotion id' you provide must match in both feeds.
The 'promotion id' should not contain spaces or symbols (e.g., %, !, etc.).
To add multiple 'promotion id' values to an item, submit the values separated by commas in the 'promotion id'.

**Comment by schnere** [comment]
You will have to wrap the promotion id into a custom attribute: https://github.com/google/google-api-php-client/issues/512
