### ISSUE TITLE
Google Content Api v2 Redirect not working

### ISSUE THREAD

**Issue by darrelljr00** [bluevisiontec/GoogleShoppingApi#44]
Im logged into my magento admin and when clicking google content api v2 / manage items... I am redirected to go to the google page to accept or cancel managing product listings. Clicking accept redirects me back to my home page. 

when I remove my client id or client secret the redirect works and I am able to add products to google api. They dont upload because of the lack of client id though. im guessing it is an authentication issue but not sure where. Please help

**Comment by darrelljr00** [comment]
on autoload.php I get this error: 
Deprecated: google-api-php-client's autoloader was moved to src/Google/autoload.php in 1.1.3. This redirect will be removed in 1.2. Please adjust your code to use the new location. in /home/darrell1/public_html/vendor/google/apiclient/autoload.php on line 25

**Comment by lewisak** [comment]
Try using API Client version 1.1.2, here - 

 https://github.com/google/google-api-php-client/archive/1.1.2.tar.gz

**Comment by darrelljr00** [comment]
I have 1.1.2 installed in     magentostore.com/vendor/google/apiclient/ .. issue still remains

**Comment by darrelljr00** [comment]
When installing composer it is asking to specify the root folder. Im not sure what to input. ((please define your magento root dir))

My magento is installed in root folder:    magentostore.com/

**Comment by darrelljr00** [comment]
Can anyone help with this issue? Ive been working on this for days. The authentication is not working. I dont know why but its not forwarding the security information to google

**Comment by schnere** [comment]
Please check the settings in Google developers console. Ensure that the redirect URL is set correctly:

https://www.yourmagentobackend.com/index.php/admin/googleShoppingApi_oauth/auth/

**Comment by Toweringmedia-clients** [comment]
We had the same issue were stuck on it all day. I finally downloaded a working copy from another clients site and uploaded it, It was a older version of the bluevisiontec file set from about a year ago. I used the 1.1.4 vender files, then it was the last file I uploaded the js file and it worked!. I hope this helps someone.
