### ISSUE TITLE
magento shopping api v2 

### ISSUE THREAD

**Issue by Toweringmedia-clients** [bluevisiontec/GoogleShoppingApi#45]
Hi,
I installed this on two stores and am getting the following issue on both, Please advise I am stuck!!

Fatal error: Class 'Google_Auth_AssertionCredentials' not found in xxx/public_html/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/GoogleShopping.php on line 107

**Comment by schnere** [comment]
Hi,

did you install using composer?
Is your Google API client for PHP on 1.1.4?
Did you apply the following patch?

```
--- vendor/google/apiclient/src/Google/Client.php.orig  2015-06-10 12:15:08.937391432 +0200
+++ vendor/google/apiclient/src/Google/Client.php       2015-06-10 12:15:47.693520083 +0200
@@ -16,7 +16,7 @@
  */

 if (!class_exists('Google_Client')) {
-  require_once dirname(__FILE__) . '/../autoload.php';
+  require_once dirname(__FILE__) . '/autoload.php';
 }

 /**
```

If you can answer everything with yes, please uncomment the " if (!class_exists('Google_Client')) {" and the ending culry bracket...

**Comment by Toweringmedia-clients** [comment]
Hi Schnere,
I can't believe you responded so quickly!!!

I did not install it using composer manual install.
I did make those changes just removing the ../
It looks like I downloaded 1.1.2 I will look for 1.1.4

**Comment by schnere** [comment]
You can also try to download the following revision:
https://github.com/google/google-api-php-client/archive/69704f981ea14ecdb603f2f875ec262a148706d2.zip

Here you won't have to apply the patch since it was fixed after release of 1.1.4 ...

**Comment by Toweringmedia-clients** [comment]
I think that got me past that issue. Now I am getting a report Error refreshing the OAuth2 token, message:

**Comment by schnere** [comment]
Which message?

Did you follow the installation guide in the Readme?
Which way did you choose - service account or client id for web application?

Did you enter your data in the module's configuration correctly?

**Comment by Toweringmedia-clients** [comment]
I chose service account for automation, I am pretty darn sure I entered it all correctly. I can delete it and start over just to be sure.

**Comment by schnere** [comment]
The message would be interesting...

Did you upload the .p12 file? Can you see it on your server? ([magento_root]/var/bluevisiontec/googleshoppingapi/oauth/)
Did you enter the correct passphrase for the .p12 file?

**Comment by Toweringmedia-clients** [comment]
Deleted the .p12 key made a new one and it worked!! 

Schnere I hope to see this on the magentoconect soon! Thanks for your hard work on this and for the quick response.
Thanks Again!!

**Comment by schnere** [comment]
You're welcome - thanks for using the module :)
