### ISSUE TITLE
Fatal error: Call to a member function setConfig() on a non-object in app/code/core/Mage/GoogleShopping/Model/Service.php on line 66

### ISSUE THREAD

**Issue by jitendrasaini** [bluevisiontec/GoogleShoppingApi#47]
Hi,

When i am trying to update any product from admin. i am getting the following fatal error. 

Fatal error: Call to a member function setConfig() on a non-object in app/code/core/Mage/GoogleShopping/Model/Service.php on line 66

On line#66, the code is  - 
$client->setConfig($configTimeout);

Please help as i am not able to update any product.

**Comment by schnere** [comment]
Hi,

the error is generated by the original Magento GoogleShopping module. If you don't need it anymore, please disable it:
[MAGENTO_ROOT]/app/etc/modules/Mage_GoogleShopping.xml 

Change `<active>true</active>` to `<active>false</active>` and clear your Magento cache (`rm -r var/cache`)

**Comment by jitendrasaini** [comment]
Ok.. the fatal error has now gone but i am getting following message when i update the product.

Product was not updated on GoogleShopping for at least one store. Please authenticate and save the product again or update manually.

Also, when i check the product after few minutes, the changes i made reverted back. For example, i am setting the Stock Availability to 'Out of Stock' but after some time it get back to 'In Stock'.

Please help!

**Comment by schnere** [comment]
The message is just a notice. Do you have more than one store? Did you open "Google Content API V2 -> Manage Items" before saving the product?
Is your stock for the product 0 or below? If not Magento might change automatically to "In Stock" ....

**Comment by jitendrasaini** [comment]
I have only one store. 
No I did not open "Google Content API V2 -> Manage Items" before saving the product.
I am trying to set the Inventory => Qty to ZERO and Stock Availability to  'Out of Stock'

**Comment by schnere** [comment]
If you open "Google Content API V2 -> Manage Items" you will be redirected to Google OAuth to allow Content API access. After that you shouldn't see the message if you save the product.
There shouldn't be any changes reverted. When the availability is set to "In Stock" is the qty 0?

**Comment by jitendrasaini** [comment]
Previously, the qty of the item was 6 and Stock Availability was  'In Stock'
When i change the qty to ZERO and set the Stock Availability to 'Out of Stock' and click the 'Save' button, i got the 2 messages below - 

Product was not updated on GoogleShopping for at least one store. Please authenticate and save the product again or update manually.

The product has been saved.

![screenshot](https://cloud.githubusercontent.com/assets/11040914/8352490/259cf552-1b53-11e5-92b1-16993e59c6d6.png)

After few minutes, when i check that product, its qty reverted back to 6 and Stock Availability to 'In Stock'.

Is it due to any sync issue between Magento and Google Shopping?

For you information, i am getting message in notifications - 

Errors happened during synchronization with Google Shopping
Cannot update 1 items.
Expected response code 200, got 404 for product 'Product Test' (in 'My Shop' store). Not Found for product 'Product Test' (in 'My Shop' store)

Product synchronization with Google Shopping completed
Total of 0 items(s) have been deleted; total of 0 items(s) have been updated. 

Google Shopping Error
For information on Google's required attributes for different product categories, please see this link: http://www.google.com/support/merchants/bin/answer.py?answer=1344057

**Comment by schnere** [comment]
Do you see the product in your Google Shopping Account? Do you see the product in Catalog -> Google Content API V2 -> Manage Items in the "Google Content Items" grid (the top one)?

There is no sync from Google Shopping to Magento, so there cannot be any issue. Your issue might not be related with the module...

**Comment by jitendrasaini** [comment]
Yes, i can see that product in Catalog -> Google Content API V2 -> Manage Items in the "Google Content Items" grid (the top one)

I am not sure about the product in your Google Shopping Account. Will it be the cause of this issue if that item is not in Google Shopping Account?

**Comment by schnere** [comment]
No nothing with the module expect an uncaught expression should cause your problems.
But please try to perform the "delete" action in Catalog -> Google Content API V2 -> Manage Items for the product as it seems not to be listed in your Google Shopping account.
