### ISSUE TITLE
Fatal error: Class 'Mage_Googlecheckout_Helper_Data' not found in /home/ballews2/public_html/app/Mage.php on line 547

### ISSUE THREAD

**Issue by nitro535** [bluevisiontec/GoogleShoppingApi#48]
I had a working install, this morning I received this message when trying to add my products:
Fatal error: Class 'Mage_Googlecheckout_Helper_Data' not found in /home/ballews2/public_html/app/Mage.php on line 547

Any ideas?

Thank you!

**Comment by schnere** [comment]
This does not seem GoogleShoppingApi related. Did you uninstall or deactivate Googlecheckout?

Am 26. Juni 2015 17:49:37 MESZ, schrieb nitro535 notifications@github.com:

> I had a working install, this morning I received this message when
> trying to add my products:
> Fatal error: Class 'Mage_Googlecheckout_Helper_Data' not found in
> /home/ballews2/public_html/app/Mage.php on line 547
> 
> Any ideas?
> 
> Thank you!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bluevisiontec/GoogleShoppingApi/issues/48

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by nitro535** [comment]
No, I did not change anything before the error. After the error I updated to the latest version of GoogleShoppingApi and folowed the instructions to update the Google Content Api 1.1.4 files with the appropriate line changes.

**Comment by nitro535** [comment]
I just noticed it is only happening on products that I have added before. If I add new products it has no problem

**Comment by nitro535** [comment]
I did some digging, the problem exists only on items with the "taxable goods" tax class enabled. As soon as I disable "taxable goods" the product uploads to google just fine. I cannot however, upload to google then switch the tax class label back to "taxable goods", it gives me the same error.

**Comment by punitgadhiya** [comment]
Hi, Can you please look at issue #51?


 Thanks

**Comment by schnere** [comment]
As the module does not load any Googlecheckout helper, this is not GoogleShoppingApi related.
