### ISSUE TITLE
At the time of save product or Synchronize product from google content items it shows error "Errors happened during synchronization with Google Shopping"

### ISSUE THREAD

**Issue by punitgadhiya** [bluevisiontec/GoogleShoppingApi#51]
Once i Synchronize product from "Google Content Items" to Google Merchant account. and then if i try to save product or again try to synchronize product it shows me. error message 

`Errors happened during synchronization with Google Shopping
Cannot update 1 items.
The item "Variateur Polini | Yamaha 4T" hasn't been updated.
Invalid method Mage_Catalog_Model_Product::isDisabled(Array
(
)
)`

Magento ver. 1.6.1.0

**Comment by punitgadhiya** [comment]
hello, Can anyone look at this plz?

**Comment by schnere** [comment]
Please try the latest commit (head revision). Mage_Catalog_Model_Product::isDisabled() is not available in Magento 1.6.1.0 .
Please open new issues if you have more problems.

**Comment by punitgadhiya** [comment]
Thanks.. its working fine now.
