### ISSUE TITLE
Google Shopping XML Feed?

### ISSUE THREAD

**Issue by leobarcellos** [bluevisiontec/GoogleShoppingApi#52]
Hi! Is there a way to export the Google Shopping XML Feed using this module?

**Comment by 5mehulhelp5** [comment]
No

**Comment by 5mehulhelp5** [comment]
Extension does not have that functionality right now...
Thanks

**Comment by schnere** [comment]
@leobarcellos you mean to download the XMLs which the module generates and sends to Google?
