### ISSUE TITLE
Admin -> Catalog -> Google Content API V2 -> Manage Items Blank

### ISSUE THREAD

**Issue by silverfernz** [bluevisiontec/GoogleShoppingApi#54]
When I click on Admin -> Catalog -> Google Content API V2 -> Manage Items  I get a blank page.

Also once I have followed all the set up instructions how do I push the first list of products to google?

Cheers

**Comment by schnere** [comment]
Please post your PHP log and your Magento system.log

**Comment by jay-saint** [comment]
This sounds like the same problem I had prior to patching the google api.

```
--- vendor/google/apiclient/src/Google/Client.php.orig  2015-06-10 12:15:08.937391432 +0200
+++ vendor/google/apiclient/src/Google/Client.php       2015-06-10 12:15:47.693520083 +0200
@@ -16,7 +16,7 @@
*/

 if (!class_exists('Google_Client')) {
-  require_once dirname(__FILE__) . '/../autoload.php';
+  require_once dirname(__FILE__) . '/autoload.php';
 }

 /**
```

**Comment by k1rah** [comment]
In CE 1.9 when I go to Admin -> Catalog -> Google Content API V2 -> Manage Items,  I get a 'there was error processing your request' page. The error report says:
![error](https://cloud.githubusercontent.com/assets/13753652/9208367/0105a9e2-4028-11e5-80d9-9b10d06c30eb.png)

I have updated all files and patched the vendor/google/apiclient/src/Google/Client.php.
I have even re-created my project in Google Developer

**Comment by nguyenthixuan151** [comment]
I get same problem.
I download and copied https://github.com/google/google-api-php-client/archive/1.1.2.tar.gz to [MAGENTO_ROOT]/vendor/google/apiclient/ but I got this error in log file- require_once(/home/leifmoeinbusines/public_html/ny/vendor/google/apiclient/src/Google/autoload.php): failed to open stream: No such file or directory  in /home/leifmoeinbusines/public_html/ny/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/GoogleShopping.php on line 2

I don't see the autoload.php file in Google folder. How can I got it? Please help me! Thanks in advance!

**Comment by michaelrachlitz** [comment]
I had many issues as well with this module, one thing when I experienced this is exact issue with the blank page in 1.9.2.2, the error was this:

Not valid template file:adminhtml/default/default/template/googleshoppingapi/items.phtml

**Comment by michaelrachlitz** [comment]
Did you install by modman or composer? You should check if you allowed symlinks in your configuration.
