### ISSUE TITLE
proper way to install without using composer?

### ISSUE THREAD

**Issue by keebler-elf** [bluevisiontec/GoogleShoppingApi#56]
in a previous version i had to change some of the code to hard code my directories for the google api php cliant in the plugin. I decided to update to take advantage of the automatic feed update using the google service account. With some changes in how files are included in the update I can no longer get the plugin to work. 
I have tried using googles suggestion of adding:

```
set_include_path(get_include_path() . PATH_SEPARATOR . '/path/to/google-api-php-client/src');
```

to the plugin code but that still gives include errors. Changing /path/to/google-api-php-client/src to the correct path of course.

```
Warning: File not found: Google/Auth/AssertionCredentials.php  in /var/www/mysite.com/htdocs/lib/Varien/Autoload.php on line 94

#0 /var/www/mysite.com/htdocs/lib/Varien/Autoload.php(94): mageCoreErrorHandler()
#1 /var/www/mysite.com/htdocs/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/GoogleShopping.php(116): Varien_Autoload->autoload()
#2 /var/www/mysite.com/htdocs/app/code/community/BlueVisionTec/GoogleShoppingApi/controllers/Adminhtml/GoogleShoppingApi/ItemsController.php(54): BlueVisionTec_GoogleShoppingApi_Model_GoogleShopping->getClient()
#3 /var/www/mysite.com/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): BlueVisionTec_GoogleShoppingApi_Adminhtml_GoogleShoppingApi_ItemsController->indexAction()
#4 /var/www/mysite.com/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch()
#5 /var/www/mysite.com/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match()
#6 /var/www/mysite.com/htdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#7 /var/www/mysite.com/htdocs/app/Mage.php(684): Mage_Core_Model_App->run()
#8 /var/www/mysite.com/htdocs/index.php(87): Mage::run()
#9 {main}
```

any suggestions?

**Comment by JustinElst** [comment]
You are probably using the 2.0 version of the google-api.
You should install using the 1.1.6 release https://github.com/google/google-api-php-client/releases/tag/1.1.6 I think that will work.
Or apply my pull-request in https://github.com/bluevisiontec/GoogleShoppingApi/pull/67 and redo the magento configuration using the readme in the pull-request.

**Comment by jmmeijer** [comment]
Maybe you could update this in the readme which under "Install manually" still mentions and links to Google Content API Client for PHP Release 1.1.2

**Comment by pquerner** [comment]
See this PR for a solution https://github.com/bluevisiontec/GoogleShoppingApi/pull/75
