### ISSUE TITLE
Custom attribute

### ISSUE THREAD

**Issue by Veiote** [bluevisiontec/GoogleShoppingApi#57]
Hello,

Is there anyway to add the atribute "installment" https://support.google.com/merchants/answer/188494?hl=en in the session "Multiple Installments (Brazil Only)"

example:

"installment": {
    "months": 6,
    "amount": {
       "value": "50",
       "currency": "BRL"
    }
 } 

I tried but I stoped because of the sub-attributes.

**Comment by schnere** [comment]
Hi,

I will think about a solution, but it might take some time to get integrated in the module.

**Comment by Veiote** [comment]
Thanks!

For testing, I created installment attribute = {"months": 6, "amount": {"value": "50","currency": "BRL" } } 
but I got this error
Error calling POST ... (400) Invalid value for installment: {"months": 6, "amount": {"value": "50","currency": "BRL" } }
