### ISSUE TITLE
Composer Composer Composer ...

### ISSUE THREAD

**Issue by SchumacherFM** [bluevisiontec/GoogleShoppingApi#6]
Great module! We're currently implementing it but ... not everybody has the vendor folder inside Magento root folder ... so this won't work at nearly 90% of all Magento installations:

https://github.com/bluevisiontec/GoogleShoppingApi/blob/master/app%2Fcode%2Fcommunity%2FBlueVisionTec%2FGoogleShoppingApi%2FModel%2FGoogleShopping.php#L2

**Comment by schnere** [comment]
Hi,

thanks for the notice. I mentioned it in the Readme and suggest to install using composer.
I also think about packaging the module for Magento Connect. Therefore I might move the Google ApiClient to /lib .

**Comment by SchumacherFM** [comment]
I've refactored your module please see here: https://github.com/Zookal/GoogleShoppingApi

I also maintain my own google api client version: https://github.com/Zookal/google-api-php-client
That version is compatible to Magento

**Comment by Studiocare** [comment]
SchumacherFM - I got your incarnation running but came into 1 issue. Items are being added to Google excluding tax. I cannot see anything obvious in the code or settings, any thoughts?

**Comment by SchumacherFM** [comment]
No idea

**Comment by Studiocare** [comment]
With the way the module is set up, would you be expecting items to be posted inclusive of tax?

**Comment by Studiocare** [comment]
I found the issue (i think)...

Model > Attribute > Price.php line 36

Changed: $isSalePriceAllowed = true;//($targetCountry == 'US');
To: $isSalePriceAllowed = ($targetCountry == 'US');

Seems to be working for UK google shopping now with the correct pricing.

**Comment by schnere** [comment]
What you are doing with this is to disable the option to post a special price to Google Shopping from countries outside the US.

How do you enter the product price in Magento backend? Including or excluding tax?

And did you enter a special price for your products?

**Comment by Studiocare** [comment]
I was looking at some of the difference from the older code against the newer code and seeing if they made any difference.

It seems to work with that change though for regular pricing for some reason.

Our prices are entered excluding tax.

There is generally only ever a couple of products (out of 6500) with special pricing set up.

The APIv1 got the pricing up including tax
