### ISSUE TITLE
Product Images disappear in admin after install

### ISSUE THREAD

**Issue by doofah** [bluevisiontec/GoogleShoppingApi#62]
After installing I find that the images no longer show on the admin page.

We've passed this to our developer to take a look at.   Magento 1.9.1.1 with all of the latest patches.

Update:

If we disabled the module, refresh cache, view the product, re-enable the module then the images work.   Refreshing cache doesn't help, reindexing doesn't help.

Images do not display on Manage Products, within the product image tab but they do display on the front end.  

So far no errors in logs or apache log.

**Comment by schnere** [comment]
So the images are not displayed on the product edit tab on "Images" tab after perfoming a mouse over?
Do you see the 4 columns "Base Image","Small Image","Thumbnail","Google Shopping Image" ?

**Comment by doofah** [comment]
No, I just get a missing image icon.

Our developer says the issue is a conflict with a "Custom Admin Grids"
extension, disabling this module or the the google shopping module fixed
the product images tab.

I've asked him to provide more info here
