### ISSUE TITLE
Error on Product Item Grid

### ISSUE THREAD

**Issue by kossanah** [bluevisiontec/GoogleShoppingApi#64]
Hello,
I cant seem to get this extension to work. On the Google Content Api v2 > Manage Item
It is not possible to perform any task. Even magento menu stop work except I use browser back button and navigate away from the extension

Inspecting the code on browser I see these errors on the console
ReferenceError: Fieldset is not defined 
ReferenceError: Translate is not defined 
ReferenceError: Calendar is not defined 
ReferenceError: Ajax is not defined 
ReferenceError: $ is not defined 
ReferenceError: Calendar is not defined 
ReferenceError: varienGrid is not defined 
ReferenceError: varienGrid is not defined 
ReferenceError: Mage is not defined 
ReferenceError: $ is not defined 
TypeError: Element.addClassName is not a function 
TypeError: Element.removeClassName is not a function 
TypeError: Element.addClassName is not a function 
TypeError: Element.removeClassName is not a function 
TypeError: Element.addClassName is not a function 
TypeError: Element.removeClassName is not a function 
TypeError: Element.addClassName is not a function 
TypeError: Element.removeClassName is not a function 
TypeError: Element.addClassName is not a function 
TypeError: Element.removeClassName is not a function

**Comment by schnere** [comment]
This looks like a JavaScript problem. Please check if everything is loaded correctly:

```
/js/prototype/prototype.js
/js/varien/js.js
/js/bluevisiontec/adminhtml/googleshopping.js
```

**Comment by kossanah** [comment]
Hello,
This is the problem and I dont know how to fix it.
The various javascript files are missing because the script is making a wrong directly call

http://www.mywebsite.com/home/cpanelusername/public_html/js/prototype/prototype.js

From the link above, the domain name www.mywebsite.com has a physical server location public_html
But the reference is pullinng the apache server root for ths site user account
home/cpanelusername/public_html/

where is this code, how can it be fixed?

**Comment by schnere** [comment]
You might have the problem on all backend pages?
Did you enable JavaScript merging?

**Comment by kossanah** [comment]
Yes I have Javascript merging on. Please help

**Comment by schnere** [comment]
Did you try to turn it off for default scope?

**Comment by kossanah** [comment]
Hello,
I turned it off and its working, but I still not able to benefit from this
yet.
My store currency is different (Naira) from what is on the list.
I needed this extension for dynamic remarketing purpose only.
