### ISSUE TITLE
Patch SUPEE-6788

### ISSUE THREAD

**Issue by lewisak** [bluevisiontec/GoogleShoppingApi#65]
Hi

Is this extension compatible with the security patch released today?

This page details the potential issues with extensions being incompatible...

http://magento.com/security/patches/supee-6788-technical-details

Thanks!

**Comment by schnere** [comment]
Hi,

after a quick review of the patch I did not see any changes which might be incompatible with the module.
Futhermore I did not see any problems using the module on a patched Magento installation.

If you have any problems please post an issue.

**Comment by lewisak** [comment]
Hi

Just to let you know, the extension is working fine after the patch.

**Comment by JustinElst** [comment]
+1
Works for me too!

**Comment by pquerner** [comment]
+1 works fine with the patch (we're on 1.9.2.4)
