### ISSUE TITLE
Error fetching OAuth2 access token, message: 'invalid_client'

### ISSUE THREAD

**Issue by nige-one** [bluevisiontec/GoogleShoppingApi#7]
Hi,
I went through your setup instructions and always get above mentioned exception when trying to Catalog->Google Content API v2->Manage Items and selecting the relevant storeview.

The backend redirects me to Google which asks me to allow the access and after accepting I get Magento's frontend exception page.

I tried new API keys, tried to enter the credentials on different scopes (Main, Store, Storeview) but get always the same error.

My Magento domain setup is not that simple, but i guess it should work anyway due to me testing on Magento's different scopes. The main website (responsible for Google's callbacks) is on a different domain then the corresponding store.

Also did some Mage::Log debugging - everything looks quite normal, as far as I can tell.

Any ideas?

**Comment by schnere** [comment]
Hi,

the domain setup should not be a problem. In a Multi Store environment the Magento backend has always the same Domain. 
Please check again your Client Id&Secret. You can also try to use a different browser.

**Comment by 5mehulhelp5** [comment]
That's True because we have to include a google client api lib in /vendor/google/apiclient/
and you can get that lib form git or google site

**Comment by nige-one** [comment]
Since the stacktrace shows that Google's apiclient is triggered
`lib/Google/Client.php(124): Google_Auth_OAuth2->authenticate('xxx...')`
I don't think the problem leads into this direction.
Maybe the fact, that my merchant account isn't connected to an adwords campaign yet could be a problem?

**Comment by gmatsuoka** [comment]
There was the same problem with me.
After I check the credentials that were settas were wrong, because cache.
I took a echo in the file ../app/code/community/BlueVisionTec/GoogleShoppingApi/controllers/Adminhtml/GoogleShoppingApi/OauthController.php line 75 and 76
