### ISSUE TITLE
Error 400 redirect_uri_mismatch

### ISSUE THREAD

**Issue by jitendrasaini** [bluevisiontec/GoogleShoppingApi#73]
I am getting the Error 400 redirect_uri_mismatch.

The redirect URI in the request: https://www.mywebsite.com/index.php/adminslug/googleShoppingApi_oauth/auth/ did not match a registered redirect URI.

Please advise!

**Comment by schnere** [comment]
Please check you Google Developer's project application redirect URI configuration like mentioned in the Readme.
