### ISSUE TITLE
Invalid_grant when access to Manage Items

### ISSUE THREAD

**Issue by nguyenthixuan151** [bluevisiontec/GoogleShoppingApi#74]
Hi, 

I get this message in report file:

a:5:{i:0;s:77:"Error refreshing the OAuth2 token, message: '{
  "error" : "invalid_grant"
}'";i:1;s:1373:"#0 /public_html/vendor/google/apiclient/src/Google/Auth/OAuth2.php(309): Google_Auth_OAuth2->refreshTokenRequest(Array)
#1 /app/code/community/BlueVisionTec/GoogleShoppingApi/Model/GoogleShopping.php(139): Google_Auth_OAuth2->refreshTokenWithAssertion()
#2 /app/code/community/BlueVisionTec/GoogleShoppingApi/controllers/Adminhtml/GoogleShoppingApi/ItemsController.php(53): BlueVisionTec_GoogleShoppingApi_Model_GoogleShopping->getClient('1')
#3 /app/code/core/Mage/Core/Controller/Varien/Action.php(418): BlueVisionTec_GoogleShoppingApi_Adminhtml_GoogleShoppingApi_ItemsController->indexAction()
#4 /app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#5 l/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#6 /app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#7 /app/Mage.php(684): Mage_Core_Model_App->run(Array)
#8 /index.php(87): Mage::run('', 'store')
#9 {main}";s:3:"url";s:92:"/index.php/admin/googleShoppingApi_items/index/store/1/key/a2de682f3bc49b66f7b7d462bbd3511f/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

How can I fix it. I use service account.

**Comment by evertontst** [comment]
I have the same error

**Comment by nguyenthixuan151** [comment]
I deleted and created a service account again. It works.
I set Google Developer Project Client ID : Project ID.
Don't check on 'Enable Google Apps Domain ....' option. 
Please try.
