### ISSUE TITLE
Products don't automatically sync with google

### ISSUE THREAD

**Issue by nguyenthixuan151** [bluevisiontec/GoogleShoppingApi#76]
Hi,
I see that we have an option in the extension setting that allow automatically sync products with google. But it looks doesn't work because my products on google was expired after time.

**Comment by pquerner** [comment]
Are your cronjobs running?
Is the config "enable_autosync" enabled?

**Comment by pquerner** [comment]
I have found some issues with the cronjob myself and created new tickets for this. Maybe its something you experience too. #83 #82 #81
