### ISSUE TITLE
Does not list the products in Manage List

### ISSUE THREAD

**Issue by gmatsuoka** [bluevisiontec/GoogleShoppingApi#8]
Hello, how are you?

On entering the option "Catalog> Google Content API v2> Manage list" displays a blank page (only loads the menu and footer).

Also realized that to enter the product detail, the menu option "GoogleShopping" this does not appear in the side menu .

They can give a hint of what can be?

thanks!

![captura de tela 2015-02-25 as 09 38 53](https://cloud.githubusercontent.com/assets/1392359/6370739/3f3b902a-bcd2-11e4-801c-cac47d6ee638.png)

**Comment by schnere** [comment]
Hi,

did you empty the Cache after installing the module?
As the attribute was not created, I think the installation script was not executed...

**Comment by gmatsuoka** [comment]
Hi !

thanks for the reply!

After looking at the logs, I discovered that the file "app/design/adminhtml/base/default/template/googleshoppingapi/items.phtml" there was no copied for some reason.

Was corrected after placing the file in the folder.
