### ISSUE TITLE
Error when open Manage Items

### ISSUE THREAD

**Issue by B-PRAVEEN** [bluevisiontec/GoogleShoppingApi#80]
The first error is Cannot find Google Content API autoload file when open Manage Items.
I have moved the autoload.php to "/vendor/google/apiclient/src/Google/autoload.php" from /vendor/google/apiclient/ (as per your documentation).

But the new error is 
`Error : Fatal error: Class 'Google_Auth_AssertionCredentials' not found in /var/www/abc/data/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/GoogleShopping.php on line 116`

Checked all rewrite permission. Not using service account.

**Comment by pquerner** [comment]
What version are you running?
