### ISSUE TITLE
Fatal error: Class 'Google_Auth_AssertionCredentials' not found

### ISSUE THREAD

**Issue by guztavoalves** [bluevisiontec/GoogleShoppingApi#86]
I am getting the following error when accessing "Manage Items":

Fatal error: Class 'Google_Auth_AssertionCredentials' not found in /home/garotafi/public_html/app/code/community/BlueVisionTec/GoogleShoppingApi/Model/GoogleShopping.php on line 116

I use Magento 1.9.2.2 and Google API google-api-php-client-2.0.

![screenshot_1](https://cloud.githubusercontent.com/assets/11070237/18356288/86e402fe-75c2-11e6-8f6b-a20586c84da7.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/11070237/18356380/d1eab798-75c2-11e6-8606-f80b39ce0c00.png)

**Comment by sickdaflip** [comment]
works only with google client api <= 1.1.7

**Comment by jmmeijer** [comment]
I'm also experiencing the same issue. Updating the Google shopping php client to 1.1.7 didn't solve it. It seems it has to do with the Autoloader not being to able to find it as described in other issues. Someone has fixed a similar issue with moving the Google-folder to the Magento root-folder and editing the path in /app/code/community/BlueVisionTec/GoogleShoppingApi/Model/GoogleShopping.php

https://www.sitepoint.com/community/t/warning-include-google-client-php-failed-to-open-stream/206670

**Comment by rvelhote** [comment]
@guztavoalves PR #94 has changes related to this issue. It will work with Google API Client V2.
