### ISSUE TITLE
synchronization process fails after upgrade to version 1.9.3.1 

### ISSUE THREAD

**Issue by ktomasz** [bluevisiontec/GoogleShoppingApi#87]
Google Shopping synchronization process is running with no ends after upgrade to version 1.9.3.1 (previously 1.9.2.4).

**Comment by ktomasz** [comment]
It could be the reason that official Google Shopping Magento extension is not supported due to a problem in the core SOAP API code on Magento 1.9.3.
Has anybody got the same issue?

**Comment by schnere** [comment]
Works fine with 1.9.3.3

**Comment by ktomasz** [comment]
It must be some other reason inside my shop. Still the same issue with 1.9.3.3. Synchronization process  completes successfully by cron job but not by the button triggered. Synchronization process is running with no ends.

**Comment by schnere** [comment]
Can you try to use the shell script? Any errors?
Please use the correct storeid:
`php -f shell/googleshopping.php -- --action syncitems --storeid 1`

There is one thing you could try:
`app/code/community/BlueVisionTec/GoogleShoppingApi/controllers/Adminhtml/GoogleShoppingApi/ItemsController.php`

Change line 210 from
  `->batchSynchronizeItems($itemIds);`
to 
  `->synchronizeItems($itemIds);`

**Comment by ktomasz** [comment]
I tried to execute command shell script to run synchronization.
But the synchronization process still running so I get the return
> flag locked - synchronization process running

How is it possible to kill it?

**Comment by schnere** [comment]
`php -f shell/googleshopping.php -- --action unlock`

**Comment by ktomasz** [comment]
@schenre thank you for your response 
The process starts to run properly again. It turned out that your last advice to change the line 210 from
->batchSynchronizeItems($itemIds);
to
->synchronizeItems($itemIds);
was a bull eye in resolving the issue.
Kindly thank you.
